### ISSUE TITLE
Make credentials optional

### ISSUE THREAD

**Issue by dougmaitelli** [meichthys/uptime_kuma#21]
I use a reverse proxy to secure all my services, but I also have a separate private virtual network between these services that allow them to communicate directly to each other.
 
With that in mind, my Uptime-Kuma does not have authentication enabled, and when consumed from HA it would not have credentials.

**Comment by meichthys** [comment]
Have you tried leaving the credentials blank? I don't think it will work currently.

**Comment by dougmaitelli** [comment]
Yes, the fields are mandatory on the UI.

**Comment by meichthys** [comment]
v2.0.2 should be available on the HACS store now. 
Hopefully this helps!

**Comment by meichthys** [comment]
@dougmaitelli

Note: This will only work if you have a way to disable authentication for the `/metrics` endpoint in Uptimekuma
By default, the `/metrics` endpoint will remain behind authentication *even after disabling authentication in the UptimeKuma settings!*

There was an attempt to address the issue here, but in my testing it doesn't seem to work. YMMV tho!

**Comment by dougmaitelli** [comment]
@meichthys I am able to access `/metrics` on my uptime-kuma with credentials disabled. I will test the new version and let you know. Thanks!
