### ISSUE TITLE
[REQUEST] Sensor with all data

### ISSUE THREAD

**Issue by mefisto22** [meichthys/uptime_kuma#24]
Pls make one sensor with all data in attributes (number of down services, up servives etc).

**Comment by meichthys** [comment]
I don't think we will implement this since this integration only creates sensors for the '/metrics' endpoint of uptime kuma. If uptime kuma exposes what you want then it should show up under this integration.

There are solutions that are built into Home Assistant that should be able to help you get what you want:

https://www.home-assistant.io/integrations/group/
